name: bizne_flutter_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 4.0.2+81

environment:
  sdk: ">=3.2.5 <4.0.3"

dependencies:
  dio: ^5.4.2+1
  country_code_picker: ^3.0.0
  dropdown_button2: ^2.3.9
  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_lints: ^3.0.2
  flutter_local_notifications: ^17.0.0
  flutter_localizations:
    sdk: flutter
  flutter_polyline_points: ^2.0.0
  geolocator: ^11.0.0
  get: ^4.6.6
  google_places_flutter: ^2.0.8
  google_geocoding_api: ^1.5.0
  google_maps_flutter: ^2.6.0
  image_picker: ^1.1.2
  location: ^5.0.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  sizer: ^2.0.15
  url_launcher: ^6.2.5
  swipe_to: ^1.0.6
  webview_flutter: ^4.8.0
  device_imei: ^0.0.4+2
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  connectivity_plus: ^6.0.2
  firebase_messaging_web: ^3.8.2
  firebase_messaging_platform_interface: ^4.5.32
  firebase_analytics: ^10.10.2
  advance_pdf_viewer2: ^2.0.5+1
  tutorial_coach_mark: ^1.2.11
  flutter_stripe: ^10.1.1
  image_cropper: ^5.0.1
  qr_code_scanner: ^1.0.1
  device_info_plus: ^10.1.0
  device_uuid: ^0.0.4
  custom_info_window: ^1.0.1
  flutter_svg: ^2.0.10+1
  _flutterfire_internals: ^1.3.33
  win32_registry: ^1.1.3
  webview_flutter_wkwebview: ^3.13.1
  path_provider: ^2.1.3
  webview_cookie_manager: ^2.0.6
  http: ^1.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.jpg"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
    - assets/map_style.json

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-VariableFont_wght.ttf
    - family: Rajdhani
      fonts:
        - asset: assets\fonts\Rajdhani-Bold.ttf
